version: "3.9"

networks:
  hw2-2:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_hw2_2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '${DB_HOST}:5433:5432'
    networks:
      - hw2-2